export const PROFESSIONAL_SECTORS = [
    'Emergency',
    'Plumber',
    'Electrician',
    'Roofer',
    'Builder',
    'Gardener',
    'Painter / Decorator',
    'Landscaper',
    'Carpenter',
    'Plasterer',
    'Driveways / Patios / Paths',
    'Fencing / Gates',
    'Tree Surgeon',
    'Handyman',
    'Locksmith',
    'Bathrooms',
    'Tiler - Tiling',
    'Central Heating',
    'Gas Boiler Servicing / Repair',
    'Other',
];
